# This file configures the analyzer, which statically analyzes Dart code to
# check for errors, warnings, and lints.
#
# The issues identified by the analyzer are surfaced in the UI of Dart-enabled
# IDEs (https://dart.dev/tools#ides-and-editors). The analyzer can also be
# invoked from the command line by running `flutter analyze`.

# The following line activates a set of recommended lints for Flutter apps,
# packages, and plugins designed to encourage good coding practices.
include: package:flutter_lints/flutter.yaml

analyzer:
  errors:
    prefer_single_quotes: error
    prefer_const_constructors: error
    prefer_const_declarations: error
    lines_longer_than_80_chars: error
    curly_braces_in_flow_control_structures: error
    unused_import: error

linter:
  rules:
    avoid_print: false
    prefer_single_quotes: true
    prefer_const_constructors: true
    prefer_const_declarations: true
    lines_longer_than_80_chars: true
    curly_braces_in_flow_control_structures: true
    unused_import: true




# Additional information about this file can be found at
# https://dart.dev/guides/language/analysis-options
