on:
  push:
    branches:
      - main
  workflow_dispatch:

name: "Build & Release"

env:
  FLUTTER_CHANNEL: 'stable' # 'stable', 'beta', or 'master', default to: 'stable'
  FLUTTER_VERSION: '3.0.0'
  PATH_TO_APK: 'build/app/outputs/flutter-apk/app-release.apk'
  PATH_TO_AAB: 'build/app/outputs/bundle/release/app-release.aab'
  ANDROID_PACKAGE_NAME: 'io.roley.demo'
  PROPERTIES_PATH: "./android/key.properties"

jobs:
  code-analysis-and-testing:
    name: Build & Release APK
    runs-on: macos-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '2.10.3'

      - name: Get pub dependencies
        run: flutter pub get

      - name: Flutter analyze
        run: flutter analyze

  android:
    name: Android CI/CD
    needs: code-analysis-and-testing
    runs-on: macos-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Prepare key.jks & key.properties files
        env:
          KEYSTORE_FILE: ${{ secrets.KEYSTORE_FILE }}
          KEY_PROPERTIES_FILE: ${{ secrets.KEY_PROPERTIES_FILE }}
        run: |
          echo "Convert key base64 string to a file KEYSTORE_FILE"
          echo "$KEYSTORE_FILE" >> key.jks.base64
          echo "Convertion Completed KEYSTORE_FILE"

          echo "Convert key.properties string to a file"
          echo "$KEY_PROPERTIES_FILE" >> key.properties
          echo "Convertion Completed KEY_PROPERTIES_FILE"

          echo "Convert key.jks secret string to a file"
          base64 --decode key.jks.base64 > key.jks
          echo "Convertion Completed key.jks"
        working-directory: 'android/'

      - name: set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11


      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: ${{ env.FLUTTER_CHANNEL }}


      - name: Build APK
        run: flutter build apk --release

      - name: Upload APK artifact
        uses: actions/upload-artifact@v3
        with:
          name: release-apk
          path: ${{ env.PATH_TO_APK }}

      - name: Build AAB
        run: flutter build appbundle --release

      - name: Upload AAB artifact
        uses: actions/upload-artifact@v3
        with:
          name: release-aab
          path: ${{ env.PATH_TO_AAB }}



